Add input file tests and fix some bugs in already exists

diff --git a/test_templates/template_result_file_output_file b/test_templates/template_result_file_output_file
--- a/test_templates/template_result_file_output_file
+++ b/test_templates/template_result_file_output_file
@@ -1,11 +1,16 @@
 if [ $# -ne 5 ]
 then
-    echo "Incorrect test usage. Expected <exec file with args> <return code> <line with output> <output file> <file with expected output data>"
+    echo "Incorrect test usage. Expected <exec file with args> <return code> <file with expected console output> <output file> <file with expected output data>"
     exit 1
 fi
 
+if [ ! -f $3 ]; then
+    echo "Console output file not found"
+    exit 4
+fi
+
 if [ ! -f $5 ]; then
-    echo "Output file with expected data not found"
+    echo "File with expected output data not found"
     exit 3
 fi
 
@@ -26,8 +31,8 @@ then
 else
     echo "Passed args:"
     echo $*
-    echo $res > ./tmp.txt
-    echo "Incorrect answer: expected return code=\""$(ret)"\", received=\""$(ret_code)"\""
+    echo "$res" > ./tmp.txt
+    echo "Incorrect answer: expected return code=\""$ret"\", received=\""$ret_code"\""
     echo "Output difference:"
     echo $(diff $3 ./tmp.txt)
     echo "Result file difference:"
